name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --watchAll=false

      - name: Build project
        run: npm run build

      - name: Deploy to EC2 Instance 1
        env:
          HOST: ${{ secrets.EC2_FRONTEND_HOST_1 }}
          USERNAME: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "$KEY" > key.pem
          chmod 600 key.pem
          scp -i key.pem -r build/* $USERNAME@$HOST:/var/www/html/
          rm key.pem

      - name: Deploy to EC2 Instance 2
        env:
          HOST: ${{ secrets.EC2_FRONTEND_HOST_2 }}
          USERNAME: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "$KEY" > key.pem
          chmod 600 key.pem
          scp -i key.pem -r build/* $USERNAME@$HOST:/var/www/html/
          rm key.pem