name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: hello-world-frontend

      - name: Run tests
        run: npm test -- --watchAll=false
        working-directory: hello-world-frontend

      - name: Build project
        run: npm run build
        working-directory: hello-world-frontend

      - name: Create .ssh directory
        run: mkdir -p ~/.ssh

      - name: Add EC2 Instance 1 to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_FRONTEND_HOST_1 }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2 Instance 1
        env:
          HOST: ${{ secrets.EC2_FRONTEND_HOST_1 }}
          USERNAME: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "$KEY" > key.pem
          chmod 600 key.pem
          scp -i key.pem -r hello-world-frontend/build/* $USERNAME@$HOST:/home/$USERNAME/
          ssh -i key.pem $USERNAME@$HOST 'sudo cp -r /home/$USERNAME/* /usr/share/nginx/html/ && sudo systemctl restart nginx'
          rm key.pem

      - name: Add EC2 Instance 2 to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_FRONTEND_HOST_2 }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2 Instance 2
        env:
          HOST: ${{ secrets.EC2_FRONTEND_HOST_2 }}
          USERNAME: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "$KEY" > key.pem
          chmod 600 key.pem
          scp -i key.pem -r hello-world-frontend/build/* $USERNAME@$HOST:/home/$USERNAME/
          ssh -i key.pem $USERNAME@$HOST 'sudo cp -r /home/$USERNAME/* /usr/share/nginx/html/ && sudo systemctl restart nginx'
          rm key.pem
